collections:
  founders:
    output: false
  boardmembers:
    output: false
  advisoryboard:
    output: false
  halloffame:
    output: false
  photogalleries:
    output: true
  officers:
    output: false
